### ISSUE TITLE
Error starting "-c" - Puppeterr

### ISSUE THREAD

**Issue by Bouchar214** [OXDBXKXO/akamai-toolkit#2]
Hey,
I try to test the custom script by default but I'm getting the next error:
`browser.js: startPuppeteer
Failed to launch the browser process! spawn node_modules/puppeteer/.local-chromium/linux-848005/chrome-linux/chrome ENOENT

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md`

Do you have any ideas how to fix it?
I'm using the latest version of node & npm

**Comment by OXDBXKXO** [comment]
ENOENT means that the file does not exist. You must check the chromePath variable in `config.json`. Puppeteer probably changed the default Chrome revision shipped with the core package so you may have to change it

**Comment by OXDBXKXO** [comment]
Shipped Chrome revision changed from 848005 to 856583 with Puppeteer 8.0.0, hence the ENOENT. Pushed a fix but the `chromePath` will break at each Puppeteer update so you should try to understand how the code works to fix it yourself :+1:
