### ISSUE TITLE
Challenge Solving

### ISSUE THREAD

**Issue by roger-alves93** [OXDBXKXO/akamai-toolkit#5]
Hello OXDBXKXO,

I'm using your application to verify my generated sensor_data, and with a few tweaks a could get a satisfying result, besides the challenges. (Brazilian Nike uses just the Challenge 2, sometimes Akamai return to me a valid cookie, sometimes don't).

I have one question: as far I read your code, you have the function to verify the challenges, via `Abck.bdm(t, a)`, so there is no way I can generate a valid solution based on your implementation? I must find some way of doing with the data coming from `mn_abck`, `mn_ts`  and `ms_psn` right?

Thank you very much for this repository, already help me a lot.

**Comment by OXDBXKXO** [comment]
If Akamai script allows three simultaneous challenges solving, in pratice you will pratically always get a challenge 2.
About challenges, as my script is only checking challenges solutions, I only need to use `bdm(t, a)`. To generate solutions yourself, you will have to understand how the `bdm` function is used in Akamai script and how the various challenge-related arrays are populated.
