### ISSUE TITLE
Issue with version extraction and webgl parameters parsing

### ISSUE THREAD

**Issue by linostar** [OXDBXKXO/akamai-toolkit#7]
I found two small issues:
- version and api hash extraction is incorrect by one char for versions that are 3-char long (such as "1.7")
- webgl parameter extraction is also incorrect when renderer (wr) value contains commas

I made a pull request https://github.com/OXDBXKXO/akamai-toolkit/pull/6 that patch those issues.

**Comment by OXDBXKXO** [comment]
Just accepted your PR, thanks !
