### ISSUE TITLE
new version of Akamai.

### ISSUE THREAD

**Issue by cbxhpy** [OXDBXKXO/akamai-toolkit#9]
Esurance has an updated version of Akamai.
https://www.esurance.com/qlnA0X/jitUj/RHFJ-/Mg/3Eup8kLNN1OV/ag8GYDNC/Wzh2RQ/gRDVAB

can't parse use akamai toolkit。

**Comment by dzcpy** [comment]
Is it v2.0?

**Comment by dzcpy** [comment]
Are you working on it? If interested maybe we can work together

**Comment by OXDBXKXO** [comment]
I no longer work on antibot solutions, this project won't be updated for Akamai v2
